Report original AccessoryInformation if device is of type HomeKit Controller
swttt/com.swttt.homekit pull request #200
Opened 2021-08-06 18:56 UTC by TheRealLink

2021-08-07 10:49 UTC, robertklep commented
Thanks :D Can you provide a squashed commit?

2021-08-07 19:34 UTC, TheRealLink commented
> Thanks :D Can you provide a squashed commit?

You are welcome :)

Do you have squash merging enabled? This should do the trick: https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

2021-08-08 06:11 UTC, robertklep commented
The issue isn't with merging, the issue is that more than a single commit makes it difficult to review your changes. So if you can squash your commits, it should come out as a single commit which makes my life easier :D

2021-08-17 06:26 UTC, robertklep commented
@TheRealLink can you take a look at the remark I posted about `CarbonMonoxideSensor`? If you can push a fix for that I'll test and merge your PR 👍🏻

2021-08-17 06:44 UTC, TheRealLink commented
> @TheRealLink can you take a look at the remark I posted about `CarbonMonoxideSensor`? If you can push a fix for that I'll test and merge your PR 👍🏻

Sure thing, but unfortunately there is no remark present ;)

2021-08-17 06:45 UTC, robertklep requested changes

2021-08-17 06:45 UTC, robertklep commented
@TheRealLink how about now? 😅

2021-08-17 06:53 UTC, TheRealLink commented on lib/devices/sensor.js
> +      .addService(Service.CarbonDioxideSensor, device.name);
Done!

2021-08-17 06:53 UTC, merged

2021-08-17 07:05 UTC, robertklep commented
I just published v3.2.0 to the test channel: https://homey.app/a/com.swttt.homekit/test/